# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "diversified-negotiation-app"
client_id = "197d20a47ef719926b6ecdc98df95e88"
application_url = "https://kodak-virgin-bend-legs.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://kodak-virgin-bend-legs.trycloudflare.com/auth/callback",
  "https://kodak-virgin-bend-legs.trycloudflare.com/auth/shopify/callback",
  "https://kodak-virgin-bend-legs.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-14d32e3a.myshopify.com"
